repos:
  # - repo: https://github.com/pre-commit/pre-commit-hooks
  #   rev: v4.5.0
  #   hooks:
  #     - id: trailing-whitespace  # Remove espaços em branco no final das linhas
  #     - id: end-of-file-fixer  # Garante uma linha em branco no final dos arquivos
  #     - id: check-yaml  # Valida arquivos YAML
  #     - id: check-json  # Valida arquivos JSON
  #     - id: debug-statements  # Impede commits com print() e pdb.set_trace()

  # # Organização automática dos imports
  # - repo: https://github.com/PyCQA/isort
  #   rev: 5.13.2
  #   hooks:
  #     - id: isort

  # # Formatação automática em black
  # - repo: https://github.com/psf/black
  #   rev: 24.3.0
  #   hooks:
  #     - id: black

  # # Análise de código estático para detectar problemas
  # - repo: https://github.com/PyCQA/flake8
  #   rev: 6.1.0
  #   hooks:
  #     - id: flake8
  #       args: ["--max-line-length=88", "--ignore=E203,W503"]

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          [
            "-rn", # Only display messages
            "-sn", # Don't display the score
            "--rcfile=pylintrc", # Link to your config file
            "--load-plugins=pylint.extensions.docparams", # Load an extension
          ]

  # # Tipagem estática
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.9.0
  #   hooks:
  #     - id: mypy
  #       args: ["--ignore-missing-imports"]

  # # Commits semânticos
  # - repo: https://github.com/commitizen-tools/commitizen
  #   rev: v3.12.0
  #   hooks:
  #     - id: commitizen
  #       args: ["check"]
